/*------------------------------------------------------------
Author:         Simran Singh
Company:        UST Gobal
Description:    Exception class for REST API classes
Test Class:
History
<Date>      <Authors Name>      <Brief Description of Change>
04-Apr-18   Simran Singh        Created for BSS-186
------------------------------------------------------------*/
public class RESTException extends Exception {}